sudo: false
language: scala
scala:
  - "2.11.8"
  - "2.10.6"
jdk:
  - "oraclejdk8"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
